### PR TITLE
Using "pagehide" because of the deprecation of unload event.

### PR DESCRIPTION
**Pull request by sjasaniel**
Using "pagehide" because of the deprecation of unload event.
https://developer.chrome.com/docs/web-platform/deprecating-unload#:~:text=The%20unload%20event%20will%20be,flags%2F%23deprecate%2Dunload%20flag

### CODE REVIEW

**Comment by tmcconechy** [comment]
@sjasaniel should we merge?

**Comment by bthharper** [comment]
@tmcconechy  - bit confused as to why we are changing what looks to be a minified file, is this generated from some source somewhere?

**Comment by tmcconechy** [comment]
@bthharper yeah this is really old code. But at the time i included a minified plugin in the code (thinking it was a good idea to save space). So it is correct here and this fixed a deprecated message.

WIll just merge

**Comment by sjasaniel** [comment]
> @sjasaniel should we merge?

Thanks Tim!

**Pull request merged**
